import { join } from 'node:path';

import type { PlopTypes } from '@turbo/gen';

import { readList, readString } from '../shared/answers.ts';
import { addTemplates, assertAbsent } from '../shared/files.ts';
import { installAction } from '../shared/install.ts';
import { policyEntry } from '../shared/policy.ts';
import { consumersPrompt, namePrompt } from '../shared/prompts.ts';
import { packageName, type Repo, workspaceName } from '../shared/repo.ts';
import type { Variant } from '../shared/variant.ts';

/**
 * Renders `packages/<name>-proto`: a `.proto` file whose TypeScript (`ts-proto`, Nest flavour) is generated by
 * `buf` into `src` and compiled to `dist`. Shared with `service`'s gRPC mode.
 */
export const protoActions = (root: string, protoName: string): PlopTypes.ActionType[] => [
  assertAbsent(root, `packages/${protoName}-proto`),
  addTemplates('proto', join(root, 'packages', `${protoName}-proto`), { protoName }),
];

export const proto = ({ root, workspaces }: Repo): Variant => ({
  kind: 'proto',
  description: 'A gRPC API package (.proto plus generated TypeScript)',
  prompts: [
    namePrompt(root, 'gRPC API', name => `packages/${name}-proto`),
    consumersPrompt(workspaces),
  ],
  actions: answers => {
    const name = readString(answers, 'name');
    const proto = `${name}-proto`;
    return [
      ...protoActions(root, name),
      policyEntry(root, { name: proto, paths: [`packages/${proto}`] }),
      installAction(root, {
        dependencies: readList(answers, 'consumers').map(consumer => ({
          consumer: workspaceName(root, consumer),
          dependency: packageName(proto),
          workspace: `packages/${proto}`,
        })),
        builds: [packageName(proto)],
      }),
    ];
  },
});
