import fs from 'node:fs';
import path from 'node:path';

import { allocateDebugPorts } from '#genProcfile';
import { monoRepoRoot } from '#utils';

/**
 * VSCode launch configuration interface - flexible to accommodate different debugger types
 */
interface LaunchConfiguration {
  name: string;
  type: string;
  request: string;
  // Mark auto-generated configurations
  __autoGenerated?: boolean;
  // Allow any other properties that VSCode launch configs might have
  [key: string]: unknown;
}

interface LaunchJson {
  version: string;
  configurations: LaunchConfiguration[];
  // Allow any other top-level properties
  [key: string]: unknown;
}

/**
 * Updates the VSCode launch.json file with debug configurations for the specified service
 */
export function updateLaunchConfigForDebugService(serviceName: string): void {
  const launchJsonPath = path.join(monoRepoRoot, '.vscode/launch.json');
  const debugPorts = allocateDebugPorts();
  const serviceDebugPort = debugPorts[serviceName];

  if (!serviceDebugPort) {
    return;
  }

  let launchConfig: LaunchJson;

  // Read existing launch.json or create default structure
  try {
    const content = fs.readFileSync(launchJsonPath, 'utf8');
    launchConfig = JSON.parse(content) as LaunchJson;
  } catch {
    // Create default structure if file doesn't exist or is invalid
    launchConfig = {
      version: '0.2.0',
      configurations: [],
    };
  }

  // Remove all existing auto-generated configurations (we only want one at a time)
  launchConfig.configurations = launchConfig.configurations.filter(config => !config.__autoGenerated);

  // Add new configuration for the selected service
  launchConfig.configurations.push({
    name: `Debug ${serviceName}`,
    type: 'node',
    request: 'attach',
    port: serviceDebugPort,
    address: 'localhost',
    skipFiles: ['<node_internals>/**'],
    sourceMaps: true,
    restart: true,
    __autoGenerated: true,
  });

  // Ensure .vscode directory exists
  fs.mkdirSync(path.join(monoRepoRoot, '.vscode'), { recursive: true });

  // Write updated launch.json
  fs.writeFileSync(launchJsonPath, JSON.stringify(launchConfig, null, 2));
}
