import { type ChildProcess, spawn } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

import type { Compiler, Configuration, RspackPluginInstance, Stats } from '@rspack/core';

export interface NestAppOptions {
  /** Defaults to `./src/main.ts`. */
  entry?: string;
}

interface CliArgv {
  mode?: Configuration['mode'];
  watch?: boolean;
}

// Workspace packages (`@example/*`) and the app's own files are bundled; everything else stays a runtime
// import from node_modules. Nest and its peers must stay external so every module shares one instance.
const isBundled = (request: string): boolean =>
  request.startsWith('.') || request.startsWith('/') || request.startsWith('#') || request.startsWith('@example/');

/**
 * `pnpm start` with "Enable Debugging" sets ENABLE_NODE_DEBUGGING and DEBUG_SERVICE, and the Procfile gives each
 * process its LABUILD_COORDINATOR_PROC_NAME and a static LABUILD_DEBUG_PORT. Only the chosen service opens an
 * inspector.
 */
const inspectPort = (): number | undefined => {
  if (process.env.ENABLE_NODE_DEBUGGING !== 'true') {
    return undefined;
  }
  const debugService = process.env.DEBUG_SERVICE || 'api-rspack';
  if (process.env.LABUILD_COORDINATOR_PROC_NAME !== debugService) {
    return undefined;
  }
  return Number.parseInt(process.env.LABUILD_DEBUG_PORT ?? '', 10) || 9229;
};

interface StartMessage {
  /** File URL of the bundle to run. */
  main: string;
  inspectPort: number | undefined;
}

/**
 * Every app process starts as a standby: it loads the app's third-party modules (the bundle's externals), which is
 * most of a start, then waits to be told which bundle to run. It exits with the dev server rather than lingering as
 * an orphan, like labuild's `run` in Lattice.
 */
const standbyScript = (externals: string[]): string => `// Generated by @example/rspack-configs. Started by \`labuild dev\`.
process.on('disconnect', () => process.exit(0));
const preload = Promise.allSettled(${JSON.stringify(externals)}.map(specifier => import(specifier)));
process.once('message', async ({ main, inspectPort }) => {
  // Opened now rather than with --inspect, because the previous app still held the port while this one waited.
  if (inspectPort !== undefined) (await import('node:inspector')).open(inspectPort, '127.0.0.1');
  await preload;
  process.channel?.unref();
  await import(main);
});
`;

/** Third-party modules the bundle imports at runtime, e.g. `@nestjs/core`. */
const externalsOf = (stats: Stats): string[] =>
  // `cachedModules`, because watch-mode stats otherwise only list the modules this rebuild touched.
  (stats.toJson({ all: false, modules: true, cachedModules: true }).modules ?? []).flatMap(({ name }) => {
    const match = name === undefined ? null : /^external "(.+)"$/.exec(name);
    return match?.[1] === undefined ? [] : [match[1]];
  });

const isRunning = (child: ChildProcess | undefined): child is ChildProcess =>
  child !== undefined && child.exitCode === null && child.signalCode === null;

/**
 * Restarts the app after every rebuild in watch mode, in a fresh process each time. In-process reloading (HMR) keeps
 * the module state of Nest, GraphQL and other dependencies across reloads, which leaks memory with every change.
 *
 * Restarts stay fast because the next process is always waiting in standby with its dependencies loaded, so a
 * restart only costs running the new bundle and Nest's bootstrap. The standby costs an idle process per app;
 * `LABUILD_STANDBY=false` skips it, and each restart then loads the dependencies itself.
 */
class RunAppPlugin implements RspackPluginInstance {
  private app: ChildProcess | undefined;
  private standby: ChildProcess | undefined;
  private standbyExternals = '';
  private restarting = false;

  apply(compiler: Compiler): void {
    compiler.hooks.done.tap('RunAppPlugin', stats => {
      if (stats.hasErrors()) {
        return;
      }
      const outputPath = stats.compilation.outputOptions.path ?? 'dist';
      const standbyPath = join(outputPath, 'standby.mjs');
      const externals = externalsOf(stats);
      if (JSON.stringify(externals) !== this.standbyExternals) {
        // The app's dependencies changed, so a waiting standby has the wrong ones loaded.
        this.standby?.kill();
        this.standby = undefined;
        this.standbyExternals = JSON.stringify(externals);
        writeFileSync(standbyPath, standbyScript(externals));
      }

      const spawnStandby = (): ChildProcess =>
        // The bundle is written next to the standby, so bare imports resolve from the app's node_modules.
        spawn(process.execPath, ['--enable-source-maps', '--env-file-if-exists=.env.development', standbyPath], {
          stdio: ['inherit', 'inherit', 'inherit', 'ipc'],
        });

      const useStandby = process.env.LABUILD_STANDBY !== 'false';
      const start = (): void => {
        this.restarting = false;
        const next = isRunning(this.standby) ? this.standby : spawnStandby();
        const message: StartMessage = {
          main: pathToFileURL(join(outputPath, 'main.js')).href,
          inspectPort: inspectPort(),
        };
        next.send(message);
        this.app = next;
        this.standby = useStandby ? spawnStandby() : undefined;
      };

      const app = this.app;
      if (!isRunning(app)) {
        start();
      } else if (!this.restarting) {
        // Start the new process once the old one has exited and released its ports. Rebuilds that finish in the
        // meantime share this restart.
        this.restarting = true;
        app.once('exit', start);
        app.kill();
      }
    });
    compiler.hooks.watchClose.tap('RunAppPlugin', () => {
      this.app?.kill();
      this.standby?.kill();
    });
  }
}

/**
 * Bundles a Nest app into `dist/main.js`.
 *
 * `development` mode adds the `development` condition, so workspace packages are compiled from their `src`
 * and edits to them rebuild and restart the app. `production` mode resolves compiled packages to their
 * `dist`, which turbo builds first (`build` depends on `^build`).
 */
export const nestApp =
  ({ entry = './src/main.ts' }: NestAppOptions = {}) =>
  (_env: unknown, argv: CliArgv): Configuration => {
    const development = argv.mode !== 'production';
    // Each dev process (e.g. one per server mode) gets its own output, so several can run from one app.
    const devTarget = process.env.SERVER_TYPE ?? process.env.SERVER_MODE ?? 'default';
    return {
      mode: development ? 'development' : 'production',
      target: 'node24',
      entry: { main: entry },
      devtool: 'source-map',
      output: {
        path: resolve(process.cwd(), development ? join('dist/dev', devTarget.replace(/[^\w-]/g, '-')) : 'dist'),
        filename: '[name].js',
        module: true,
        chunkFormat: 'module',
        clean: true,
      },
      externalsType: 'module-import',
      externalsPresets: { node: true },
      externals: [
        ({ request }, callback) =>
          request === undefined || isBundled(request) ? callback() : callback(undefined, request),
      ],
      resolve: {
        extensions: ['.ts', '.tsx', '.js'],
        conditionNames: development ? ['development', 'node', 'import', 'default'] : ['node', 'import', 'default'],
      },
      module: {
        rules: [
          {
            test: /\.tsx?$/,
            loader: 'builtin:swc-loader',
            options: {
              jsc: {
                target: 'es2023',
                parser: { syntax: 'typescript', tsx: true, decorators: true },
                transform: { legacyDecorator: true, decoratorMetadata: true, react: { runtime: 'automatic' } },
              },
            },
            type: 'javascript/auto',
          },
        ],
      },
      optimization: { minimize: false },
      plugins: argv.watch ? [new RunAppPlugin()] : [],
    };
  };

/** The config for a Nest app with its entry at `src/main.ts`. */
export default nestApp();
